workflows:
  build:
    name: Node.js and npm
    environment:
      node: 12
      npm: 7
      instance_type: mac_mini_m1
    scripts:
      - node -v
      - npm -v
      - npm install -g yarn
      - yarn -v

