workflows:
  build:
    name: Node.js and npm
    instance_type: windows_x2
    environment:
      node: 16.14.0
      npm: 8.3.1
    scripts:
      - node -v
      - npm -v
      - npm install -g yarn
      - yarn -v

