workflows:
  build:
    name: Build for draft pull request
    environment:
      vars:
        FOO: BAR
        VAR1: True
        VAR2: true
        VAR3: yes
        VAR4: no
        VAR5: false
    triggering:
      events:
        - pull_request
    when:
      condition: event.pull_request.draft == true
    scripts:
      - script: echo "Run for draft pull request"
        when:
          condition: event.pull_request.draft
      - script: echo "Run FOO is BAR"
        when:
          condition: baz.env.FOO == 'BAR'
      - script: echo "Run FOO is not BAR"
        when:
          condition: env.FOO != 'BAR'
      - script: echo "Run FOO is not BAZ"
        when:
          condition: env.FOO != 'BAZ'

